# Generated by Django 3.2.12 on 2022-02-22 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('mobile_operator_code', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=20)),
                ('time_zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_notification', models.DateTimeField(null=True)),
                ('message', models.TextField()),
                ('time_finish_notification', models.DateTimeField(null=True)),
                ('client_filter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_status', models.CharField(choices=[('waiting', 'Waiting'), ('sent', 'Sent'), ('error', 'Error'), ('time_is_over', 'Time_is_over')], default='waiting', max_length=60)),
                ('dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_detail', to='notifications.client')),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_detail', to='notifications.distribution')),
            ],
        ),
    ]
