version: "3.9"
   
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  web:
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # depends_on:
    #   - db
  redis:
    image: redis:alpine
  celery_worker:
    restart: always
    build: ./backend
    command: celery -A .celery_app worker -l info
    volumes:
      - ./backend:/code
    depends_on:
      - redis
  celery_beat:
    restart: always
    build: ./backend
    command: celery -A .celery_app beat -l info
    volumes:
      - ./backend:/code
    depends_on:
      - redis
